"""device update

Revision ID: 1d274621db78
Revises: 2c21ba3432b7
Create Date: 2026-06-08 14:15:19.518853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.models.push_notifications import device_platform, push_delivery_state

# revision identifiers, used by Alembic.
revision: str = '1d274621db78'
down_revision: Union[str, Sequence[str], None] = '2c21ba3432b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    device_platform.create(op.get_bind(), checkfirst=True)
    push_delivery_state.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_push_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('last_push_status', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('last_push_error', sa.Text(), nullable=True))
    op.alter_column('devices', 'platform',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('android', 'windows', name='device_platform'),
               nullable=False,
               postgresql_using='platform::device_platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'platform',
               existing_type=sa.Enum('android', 'windows', name='device_platform'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('devices', 'last_push_error')
    op.drop_column('devices', 'last_push_status')
    op.drop_column('devices', 'last_push_at')
    # ### end Alembic commands ###
    device_platform.drop(op.get_bind(), checkfirst=True)
    push_delivery_state.drop(op.get_bind(), checkfirst=True)
