"""otp

Revision ID: 21c4761d3415
Revises: f371b154f1e1
Create Date: 2026-05-03 15:45:47.198635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c4761d3415'
down_revision: Union[str, Sequence[str], None] = 'f371b154f1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('otp_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('otp_secret_enc', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_pending_secret_enc', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_last_used_step', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('otp_failed_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('otp_locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_locked_until')
    op.drop_column('users', 'otp_failed_attempts')
    op.drop_column('users', 'otp_last_used_step')
    op.drop_column('users', 'otp_pending_secret_enc')
    op.drop_column('users', 'otp_secret_enc')
    op.drop_column('users', 'otp_verified')
    op.drop_column('users', 'otp_enabled')
    # ### end Alembic commands ###
