"""document files

Revision ID: 27e430082e9e
Revises: e0b4adc3f132
Create Date: 2026-04-10 17:58:03.999225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e430082e9e'
down_revision: Union[str, Sequence[str], None] = 'e0b4adc3f132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_routes', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'approval_routes', 'companies', ['company_id'], ['id'])
    op.alter_column('document_approvals', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('document_approvals', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('document_versions', sa.Column('storage_object_name', sa.String(), nullable=False))
    op.add_column('document_versions', sa.Column('original_file_name', sa.String(), nullable=False))
    op.add_column('document_versions', sa.Column('mime_type', sa.String(), nullable=False))
    op.add_column('document_versions', sa.Column('file_size', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'document_versions', ['storage_object_name'])
    op.drop_column('document_versions', 'url')
    op.alter_column('documents', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'doc_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'doc_unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('document_versions', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_versions', type_='unique')
    op.drop_column('document_versions', 'file_size')
    op.drop_column('document_versions', 'mime_type')
    op.drop_column('document_versions', 'original_file_name')
    op.drop_column('document_versions', 'storage_object_name')
    op.alter_column('document_approvals', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document_approvals', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'approval_routes', type_='foreignkey')
    op.drop_column('approval_routes', 'company_id')
    # ### end Alembic commands ###
