"""notifications update

Revision ID: 2c21ba3432b7
Revises: 48b341318932
Create Date: 2026-06-08 11:18:31.958854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c21ba3432b7'
down_revision: Union[str, Sequence[str], None] = '48b341318932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('devices', sa.Column('push_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('devices', sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_devices_user_push_enabled', 'devices', ['user_id', 'push_enabled'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index('ix_devices_user_push_enabled', table_name='devices')
    op.drop_column('devices', 'disabled_at')
    op.drop_column('devices', 'push_enabled')
    op.drop_table('user_notification_settings')
    # ### end Alembic commands ###
