"""push_notifications

Revision ID: 33b7d78819fa
Revises: 5d6d1e39e828
Create Date: 2026-05-28 22:27:05.524844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src.models.documents import notification_status_type

# revision identifiers, used by Alembic.
revision: str = '33b7d78819fa'
down_revision: Union[str, Sequence[str], None] = '5d6d1e39e828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    notification_status_type.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('body', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notifications', sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notification_status'), server_default='pending', nullable=False))
    op.add_column('notifications', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('notifications', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    notification_status_type.drop(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'error')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'data')
    op.drop_column('notifications', 'body')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
