"""webauthn update

Revision ID: 3e2bfcb604b0
Revises: f394b3e2dfd4
Create Date: 2026-05-04 22:55:19.573582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e2bfcb604b0'
down_revision: Union[str, Sequence[str], None] = 'f394b3e2dfd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webauthn_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('challenge_b64', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webauthn_challenge_user_purpose', 'webauthn_challenges', ['user_id', 'purpose', 'consumed_at'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credential_id_b64', sa.String(length=512), nullable=False),
    sa.Column('public_key_b64', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aaguid', sa.String(length=64), nullable=True),
    sa.Column('is_platform', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webauthn_cred_user', 'webauthn_credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_webauthn_credentials_credential_id_b64'), 'webauthn_credentials', ['credential_id_b64'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_credentials_credential_id_b64'), table_name='webauthn_credentials')
    op.drop_index('ix_webauthn_cred_user', table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index('ix_webauthn_challenge_user_purpose', table_name='webauthn_challenges')
    op.drop_table('webauthn_challenges')
    # ### end Alembic commands ###
