"""users and webauthn changes

Revision ID: 48b341318932
Revises: 36c562069f07
Create Date: 2026-06-08 10:30:42.100698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b341318932'
down_revision: Union[str, Sequence[str], None] = '36c562069f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passkey_enabled')
    op.add_column('webauthn_credentials', sa.Column('device_id', sa.String(length=128), nullable=True))
    op.add_column('webauthn_credentials', sa.Column('device_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_webauthn_credentials_device_id'), 'webauthn_credentials', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_credentials_device_id'), table_name='webauthn_credentials')
    op.drop_column('webauthn_credentials', 'device_name')
    op.drop_column('webauthn_credentials', 'device_id')
    op.add_column('users', sa.Column('passkey_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
