"""company

Revision ID: 4f78f6434e42
Revises: 27e430082e9e
Create Date: 2026-04-13 17:19:53.490425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f78f6434e42'
down_revision: Union[str, Sequence[str], None] = '27e430082e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_company_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_company_id_fkey'), 'users', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
