"""passkey 

Revision ID: 5a5db7e8537a
Revises: f76431d1ae89
Create Date: 2026-05-05 20:32:08.154994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5db7e8537a'
down_revision: Union[str, Sequence[str], None] = 'f76431d1ae89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passkey_enabled', sa.Boolean(), nullable=True))
    op.drop_column('users', 'passkey_enables')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passkey_enables', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'passkey_enabled')
    # ### end Alembic commands ###
