"""document token update

Revision ID: 5d6d1e39e828
Revises: fcb7a5c6afff
Create Date: 2026-05-26 21:41:41.790917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6d1e39e828'
down_revision: Union[str, Sequence[str], None] = 'fcb7a5c6afff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_tokens_document_id_fkey'), 'document_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'document_tokens', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('document_tokens_document_id_fkey'), 'document_tokens', 'users', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
