"""Models Update

Revision ID: b28d9ce21feb
Revises: 9fa0d0206aaf
Create Date: 2026-04-02 12:27:18.022031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b28d9ce21feb'
down_revision: Union[str, Sequence[str], None] = '9fa0d0206aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_routes', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_approval_routes_id'), table_name='approval_routes')
    op.drop_constraint(op.f('approval_routes_created_by_fkey'), 'approval_routes', type_='foreignkey')
    op.create_foreign_key(None, 'approval_routes', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.add_column('document_approvals', sa.Column('document_id', sa.UUID(), nullable=False))
    op.alter_column('document_approvals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_document_approvals_id'), table_name='document_approvals')
    op.create_index('ix_doc_approval_step', 'document_approvals', ['version_id', 'step_index'], unique=False)
    op.create_foreign_key(None, 'document_approvals', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_units_id'), table_name='document_units')
    op.create_unique_constraint(None, 'document_units', ['document_id', 'unit_id'])
    op.alter_column('document_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_document_versions_id'), table_name='document_versions')
    op.create_unique_constraint(None, 'document_versions', ['document_id', 'version_number'])
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('documents', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.create_index('ix_documents_search', 'documents', ['status_id', 'category_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('documents_author_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_route_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_category_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_unit_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_status_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'approval_routes', ['route_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'statuses', ['status_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'units', ['unit_id'], ['id'])
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index('ix_notifications_user', 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_constraint(op.f('notifications_document_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_column('profiles', 'email')
    op.alter_column('refresh_tokens', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_user', 'refresh_tokens', ['user_id', 'is_revoked'], unique=False)
    op.drop_index(op.f('ix_role_categories_id'), table_name='role_categories')
    op.create_unique_constraint(None, 'role_categories', ['role_id', 'category_id'])
    op.add_column('roles', sa.Column('company_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_foreign_key(None, 'roles', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_route_edges_id'), table_name='route_edges')
    op.drop_index(op.f('ix_route_nodes_id'), table_name='route_nodes')
    op.create_unique_constraint(None, 'route_nodes', ['route_id', 'step_index'])
    op.drop_constraint(op.f('route_nodes_role_id_fkey'), 'route_nodes', type_='foreignkey')
    op.drop_constraint(op.f('route_nodes_approver_id_fkey'), 'route_nodes', type_='foreignkey')
    op.drop_constraint(op.f('route_nodes_user_id_fkey'), 'route_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'route_nodes', 'users', ['approver_id'], ['id'])
    op.drop_column('route_nodes', 'user_id')
    op.drop_column('route_nodes', 'role_id')
    op.drop_index(op.f('ix_statuses_id'), table_name='statuses')
    op.drop_index(op.f('ix_unit_companies_id'), table_name='unit_companies')
    op.create_unique_constraint(None, 'unit_companies', ['unit_id', 'company_id'])
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.alter_column('user_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_tokens_id'), table_name='user_tokens')
    op.create_index('ix_user_tokens_user_expires', 'user_tokens', ['user_id', 'expires_at'], unique=False)
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'company_id')
    op.drop_index('ix_user_tokens_user_expires', table_name='user_tokens')
    op.create_index(op.f('ix_user_tokens_id'), 'user_tokens', ['id'], unique=False)
    op.alter_column('user_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.drop_constraint(None, 'unit_companies', type_='unique')
    op.create_index(op.f('ix_unit_companies_id'), 'unit_companies', ['id'], unique=False)
    op.create_index(op.f('ix_statuses_id'), 'statuses', ['id'], unique=False)
    op.add_column('route_nodes', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('route_nodes', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'route_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('route_nodes_user_id_fkey'), 'route_nodes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('route_nodes_approver_id_fkey'), 'route_nodes', 'users', ['approver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('route_nodes_role_id_fkey'), 'route_nodes', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'route_nodes', type_='unique')
    op.create_index(op.f('ix_route_nodes_id'), 'route_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_route_edges_id'), 'route_edges', ['id'], unique=False)
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.drop_column('roles', 'company_id')
    op.drop_constraint(None, 'role_categories', type_='unique')
    op.create_index(op.f('ix_role_categories_id'), 'role_categories', ['id'], unique=False)
    op.drop_index('ix_refresh_tokens_user', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'issued_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('profiles', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_document_id_fkey'), 'notifications', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_notifications_user', table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_status_id_fkey'), 'documents', 'statuses', ['status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('documents_unit_id_fkey'), 'documents', 'units', ['unit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('documents_category_id_fkey'), 'documents', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('documents_route_id_fkey'), 'documents', 'approval_routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('documents_author_id_fkey'), 'documents', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_documents_search', table_name='documents')
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.alter_column('documents', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('documents', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'document_versions', type_='unique')
    op.create_index(op.f('ix_document_versions_id'), 'document_versions', ['id'], unique=False)
    op.alter_column('document_versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'document_units', type_='unique')
    op.create_index(op.f('ix_document_units_id'), 'document_units', ['id'], unique=False)
    op.drop_constraint(None, 'document_approvals', type_='foreignkey')
    op.drop_index('ix_doc_approval_step', table_name='document_approvals')
    op.create_index(op.f('ix_document_approvals_id'), 'document_approvals', ['id'], unique=False)
    op.alter_column('document_approvals', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('document_approvals', 'document_id')
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.drop_constraint(None, 'approval_routes', type_='foreignkey')
    op.create_foreign_key(op.f('approval_routes_created_by_fkey'), 'approval_routes', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_approval_routes_id'), 'approval_routes', ['id'], unique=False)
    op.alter_column('approval_routes', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
