"""webauthn

Revision ID: cd3b6aad4544
Revises: 21c4761d3415
Create Date: 2026-05-04 11:57:30.649531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3b6aad4544'
down_revision: Union[str, Sequence[str], None] = '21c4761d3415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('auth_level', sa.String(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('jti', sa.String(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('parent_jti', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'parent_jti')
    op.drop_column('refresh_tokens', 'jti')
    op.drop_column('refresh_tokens', 'auth_level')
    # ### end Alembic commands ###
