"""documents and tokens update

Revision ID: e0b4adc3f132
Revises: b28d9ce21feb
Create Date: 2026-04-06 16:31:08.163142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0b4adc3f132'
down_revision: Union[str, Sequence[str], None] = 'b28d9ce21feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_routes', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('companies', 'director_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('document_approvals', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('document_approvals', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('documents', sa.Column('doc_unit_id', sa.Integer(), nullable=False))
    op.alter_column('documents', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('documents', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('documents_unit_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'document_units', ['doc_unit_id'], ['id'])
    op.drop_column('documents', 'unit_id')
    op.add_column('user_tokens', sa.Column('token_type', sa.String(), nullable=False))
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('user_tokens', 'token_type')
    op.add_column('documents', sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_unit_id_fkey'), 'documents', 'units', ['unit_id'], ['id'])
    op.alter_column('documents', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('documents', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('documents', 'doc_unit_id')
    op.alter_column('document_approvals', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document_approvals', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('companies', 'director_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('approval_routes', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
