"""doc_unit

Revision ID: f371b154f1e1
Revises: 4f78f6434e42
Create Date: 2026-04-13 17:40:09.530699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f371b154f1e1'
down_revision: Union[str, Sequence[str], None] = '4f78f6434e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_doc_unit_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'doc_unit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_unit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_doc_unit_id_fkey'), 'documents', 'document_units', ['doc_unit_id'], ['id'])
    # ### end Alembic commands ###
