"""docunit

Revision ID: f4c4948585e3
Revises: 5a5db7e8537a
Create Date: 2026-05-07 21:14:22.661101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c4948585e3'
down_revision: Union[str, Sequence[str], None] = '5a5db7e8537a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_units_document_id_unit_id_key'), 'document_units', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('document_units_document_id_unit_id_key'), 'document_units', ['document_id', 'unit_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
