"""passkey

Revision ID: f76431d1ae89
Revises: 3e2bfcb604b0
Create Date: 2026-05-05 20:30:20.169198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76431d1ae89'
down_revision: Union[str, Sequence[str], None] = '3e2bfcb604b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passkey_enables', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passkey_enables')
    # ### end Alembic commands ###
